### ISSUE TITLE
Error in parsing Array params

### ISSUE THREAD

**Issue by jhollinger** [Gild/ruby-swagger#30]
Grape allows one to define a param as array of integers, strings, etc. by setting `type` to `Array[Integer]`, `Array[String]`, etc.:

    params do
      optional :primes, type: Array[Integer], desc: "Some prime numbers"
    end

ruby-swagger generates this JSON for that param:

    "primes": {
      "description": "Some prime numbers",
      "type": "object",
      "$ref": "#/definitions/[Integer]"
    }

But there's no corresponding entry under `"definitions"`, so swagger-ui chokes with:

    Uncaught TypeError: Swagger 2.0 does not support null types ([object Object]).  See https://github.com/swagger-api/swagger-spec/issues/229.

**Comment by jhollinger** [comment]
Looks like the correct swagger def for `primes` would be:

    "primes": {
      "description": "Some prime numbers",
      "type": "array",
      "items": {"type": "integer"}
    }

I haven't looked at the source yet, but I don't imagine it's a difficult fix. I'll look into creating a PR.

**Comment by alexagranov** [comment]
@jhollinger I believe I may have fixed this as of https://github.com/Gild/ruby-swagger/pull/41 which has been merged to master

**Comment by oliverzeyen** [comment]
@alexagranov #41 enhances array types to nest representers. It doesn't fix this issue. The grape short syntax `Array[Integer]`or `Array[String]` is not yet supported. I am currently working on a fix for this.

**Comment by alexagranov** [comment]
Good to hear.  Thank you.

**Comment by oliverzeyen** [comment]
#49 fixes this

**Comment by alexagranov** [comment]
:+1:
