### ISSUE TITLE
Support grape entity 0.5

### ISSUE THREAD

**Issue by namxam** [Gild/ruby-swagger#37]
grape entity changed the way they expose their documented attributes. The ```.exposures``` method is no longer available and its replacement ```.root_exposures``` seems to have a different signature.

**Comment by oliverzeyen** [comment]
I will take a look at this one now since we really need nested exposures. Currently we fix this by backporting `exposures` in `grape-entity`

**Comment by rngtng** [comment]
see backport here: https://github.com/ruby-grape/grape-entity/pull/151#issuecomment-163729340
